/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosia.vista.InicioSesion;

import javax.swing.JButton;
import javax.swing.JPasswordField;

/**
 *
 * @author geoff
 */
public class InicioSesionAdministradorP extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAlumnoEditarP
     */
    public InicioSesionAdministradorP() {
        initComponents();
        ocultarLabelError();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonIngresarAdmin = new javax.swing.JButton();
        jLabelErrorAdmin = new javax.swing.JLabel();
        jPasswordFieldAdmin = new javax.swing.JPasswordField();

        jLabel1.setText("Se necesita inicio de sesion de administrador para su acción.");

        jLabel2.setText("Contraseña:");

        jButtonIngresarAdmin.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIngresarAdmin.setText("Actualizar");

        jLabelErrorAdmin.setText("Contraseña incorrecta.");

        jPasswordFieldAdmin.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButtonIngresarAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(jPasswordFieldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabelErrorAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelErrorAdmin)
                .addGap(28, 28, 28)
                .addComponent(jButtonIngresarAdmin)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JPasswordField getjPasswordFieldAdmin() {
        return jPasswordFieldAdmin;
    }

    public JButton getjButtonIngresarAdmin() {
        return jButtonIngresarAdmin;
    }
    
    public void mostrarLabelError() {
        jLabelErrorAdmin.setVisible(true);
    }
    
    public void ocultarLabelError() {
        jLabelErrorAdmin.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresarAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelErrorAdmin;
    private javax.swing.JPasswordField jPasswordFieldAdmin;
    // End of variables declaration//GEN-END:variables
}
