/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosia.vista.InicioSesion;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author geoff
 */
public class InicioSesionProfesorP extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAlumnoRellenadoP
     */
    public InicioSesionProfesorP() {
        initComponents();
        ocultarLabelError();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldRutProfesor = new javax.swing.JTextField();
        jButtonIngresarProfesor = new javax.swing.JButton();
        jLabelErrorProfesor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButtonIngresarProfesor.setText("Buscar");

        jLabelErrorProfesor.setText("El RUT ingresado no existe, intente con otro.");

        jLabel1.setText("Se necesita inicio de sesion de profesor para su acción.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(jTextFieldRutProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(jButtonIngresarProfesor))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addComponent(jLabelErrorProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRutProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelErrorProfesor)
                .addGap(18, 18, 18)
                .addComponent(jButtonIngresarProfesor)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getjTextFieldRutProfesor() {
        return jTextFieldRutProfesor;
    }
    
    public JButton getjButtonIngresarProfesor() {
        return jButtonIngresarProfesor;
    }
    
    // Métodos para controlar el mensaje de error
    public void mostrarLabelError() {
        jLabelErrorProfesor.setVisible(true);
    }
    
    public void ocultarLabelError() {
        jLabelErrorProfesor.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresarProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelErrorProfesor;
    private javax.swing.JTextField jTextFieldRutProfesor;
    // End of variables declaration//GEN-END:variables
}
