/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista.gestionAlumnos;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author geoff
 */
public class AgregarAlumnoV extends javax.swing.JFrame {

    /**
     * Creates new form AgregarAlumnoV
     */
    public AgregarAlumnoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAgregarAlumnoVCancelar = new javax.swing.JButton();
        jTextFieldAgregarAlumnoVNombre = new javax.swing.JTextField();
        jTextFieldAgregarAlumnoVRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAgregarAlumnoVCrear = new javax.swing.JButton();
        jLabelAgregarAlumnoVExito = new javax.swing.JLabel();
        jComboBoxAgregarAlumnoVCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Esta es la ventana para agregar un alumno");

        jButtonAgregarAlumnoVCancelar.setBackground(new java.awt.Color(231, 231, 231));
        jButtonAgregarAlumnoVCancelar.setText("Cancelar");
        jButtonAgregarAlumnoVCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAlumnoVCancelarActionPerformed(evt);
            }
        });

        jTextFieldAgregarAlumnoVNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgregarAlumnoVNombreActionPerformed(evt);
            }
        });

        jTextFieldAgregarAlumnoVRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgregarAlumnoVRutActionPerformed(evt);
            }
        });

        jLabel2.setText("nombre: ");

        jLabel3.setText("curso:");

        jLabel4.setText("rut:");

        jButtonAgregarAlumnoVCrear.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAgregarAlumnoVCrear.setText("Crear alumno");
        jButtonAgregarAlumnoVCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelAgregarAlumnoVExito.setText("Alumno agregado con éxito !!");

        jComboBoxAgregarAlumnoVCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuarto medio", "Tercero medio", "Segundo medio", "Primero medio", "Octavo basico", "Septimo basico", "Sexto basico", "Quinto basico", "Cuarto basico", "Tercero basico", "Segundo basico", "Primero basico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregarAlumnoVCancelar)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAgregarAlumnoVCrear)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldAgregarAlumnoVRut, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(jTextFieldAgregarAlumnoVNombre)
                                .addComponent(jComboBoxAgregarAlumnoVCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabelAgregarAlumnoVExito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAgregarAlumnoVNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxAgregarAlumnoVCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAgregarAlumnoVRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarAlumnoVCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabelAgregarAlumnoVExito)
                .addGap(2, 2, 2)
                .addComponent(jButtonAgregarAlumnoVCancelar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarAlumnoVCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAlumnoVCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarAlumnoVCancelarActionPerformed

    private void jTextFieldAgregarAlumnoVRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgregarAlumnoVRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgregarAlumnoVRutActionPerformed

    private void jTextFieldAgregarAlumnoVNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgregarAlumnoVNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgregarAlumnoVNombreActionPerformed
    
    // sensibilizacion de botones
    public JButton getjButtonAgregarAlumnoVCancelar(){
        return jButtonAgregarAlumnoVCancelar;
    }
    
    public JButton getjButtonAgregarAlumnoVCrear(){
        return jButtonAgregarAlumnoVCrear;
    }
    
    public String getjTextFieldAgregarAlumnoVNombre(){
        return jTextFieldAgregarAlumnoVNombre.getText();
    }
    
    public JComboBox<String> getjComboBoxAgregarAlumnoVCurso(){
        return jComboBoxAgregarAlumnoVCurso;
    }
        
    public String getjTextFieldAgregarAlumnoVRut(){
        return jTextFieldAgregarAlumnoVRut.getText();
    }
    
    public void ocultarjLabelAgregarAlumnoVExito(){
        jLabelAgregarAlumnoVExito.setVisible(false);
    }
    
    public void mostrarjLabelAgregarAlumnoVExito(){
        jLabelAgregarAlumnoVExito.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarAlumnoVCancelar;
    private javax.swing.JButton jButtonAgregarAlumnoVCrear;
    private javax.swing.JComboBox<String> jComboBoxAgregarAlumnoVCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAgregarAlumnoVExito;
    private javax.swing.JTextField jTextFieldAgregarAlumnoVNombre;
    private javax.swing.JTextField jTextFieldAgregarAlumnoVRut;
    // End of variables declaration//GEN-END:variables
}
