/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista.GestionAlumnos;

import javax.swing.JButton;

/**
 *
 * @author Bruno Medina
 */
public class EliminarAlumnoV extends javax.swing.JFrame {

    /**
     * Creates new form EliminarAlumnoV
     */
    public EliminarAlumnoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEliminarAlumnoVRut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEliminarAlumnoVCancelar = new javax.swing.JButton();
        ocultarjLabelEliminarAlumnoVExito = new javax.swing.JLabel();
        jButtonEliminarAlumnoVEliminar = new javax.swing.JButton();
        ocultarjLabelEliminarAlumnoVNoExiste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rut:");

        jLabel2.setText("Ingrese el Rut del Alumno a Eliminar");

        jButtonEliminarAlumnoVCancelar.setText("Cancelar");

        ocultarjLabelEliminarAlumnoVExito.setText("Se ha Eliminado Correctamente");

        jButtonEliminarAlumnoVEliminar.setText("Eliminar Alumno");

        ocultarjLabelEliminarAlumnoVNoExiste.setText("No existe Alumno con ese RUT.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldEliminarAlumnoVRut, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ocultarjLabelEliminarAlumnoVNoExiste)
                        .addComponent(ocultarjLabelEliminarAlumnoVExito)))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEliminarAlumnoVEliminar)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEliminarAlumnoVCancelar)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEliminarAlumnoVRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarAlumnoVEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ocultarjLabelEliminarAlumnoVExito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocultarjLabelEliminarAlumnoVNoExiste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonEliminarAlumnoVCancelar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getjButtonEliminarAlumnoVEliminar(){
        return jButtonEliminarAlumnoVEliminar;
    }
    
    public JButton getjButtonEliminarAlumnoVCancelar(){
        return jButtonEliminarAlumnoVCancelar;
    }
    
    public String getjTextFieldEliminarAlumnoVRut(){
        return jTextFieldEliminarAlumnoVRut.getText();
    }
    
    public void ocultarjLabelEliminarAlumnoVNoExiste(){
        ocultarjLabelEliminarAlumnoVNoExiste.setVisible(false);
    }
    
    public void mostarjLabelEliminarAlumnoVNoExiste(){
        ocultarjLabelEliminarAlumnoVNoExiste.setVisible(true);
    }
    
    public void ocultarjLabelEliminarAlumnoVExito(){
        ocultarjLabelEliminarAlumnoVExito.setVisible(false);
    }
    
    public void mostrarjLabelAgregarAlumnoVExito(){
        ocultarjLabelEliminarAlumnoVExito.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarAlumnoVCancelar;
    private javax.swing.JButton jButtonEliminarAlumnoVEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldEliminarAlumnoVRut;
    private javax.swing.JLabel ocultarjLabelEliminarAlumnoVExito;
    private javax.swing.JLabel ocultarjLabelEliminarAlumnoVNoExiste;
    // End of variables declaration//GEN-END:variables
}
