/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista.gestionAlumnos;

import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author geoff
 */
public class ModificarAlumnoV extends javax.swing.JFrame {

    /**
     * Creates new form ModificarAlumnoV
     */
    public ModificarAlumnoV() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonModificarAlumnoVCancelar = new javax.swing.JButton();
        jPanelModificarAlumnoVPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Modificar Alumno");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonModificarAlumnoVCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanelModificarAlumnoVPrincipalLayout = new javax.swing.GroupLayout(jPanelModificarAlumnoVPrincipal);
        jPanelModificarAlumnoVPrincipal.setLayout(jPanelModificarAlumnoVPrincipalLayout);
        jPanelModificarAlumnoVPrincipalLayout.setHorizontalGroup(
            jPanelModificarAlumnoVPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanelModificarAlumnoVPrincipalLayout.setVerticalGroup(
            jPanelModificarAlumnoVPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModificarAlumnoVCancelar)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanelModificarAlumnoVPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelModificarAlumnoVPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarAlumnoVCancelar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    public void mostrarjPanelModificarAlumnoVPrincipal(){
    jPanelModificarAlumnoVInformacionRellenar.setVisible(true);
}

public void ocultarjPanelModificarAlumnoVPrincipal(){
    jPanelModificarAlumnoVInformacionRellenar.setVisible(false);
}

public String getjTextFieldModificarAlumnoVRutBuscar(){
    return jTextFieldModificarAlumnoVRutBuscar.getText();
}

public JButton getjButtonModificarAlumnoVBuscar(){
    return jButtonModificarAlumnoVBuscar;
}
*/
public JButton getjButtonModificarAlumnoVCancelar(){
    return jButtonModificarAlumnoVCancelar;
}

public JPanel getjPanelModificarAlumnoVPrincipal(){
    return jPanelModificarAlumnoVPrincipal;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarAlumnoVCancelar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelModificarAlumnoVPrincipal;
    // End of variables declaration//GEN-END:variables
}
