/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosia.vista.gestionAlumnos;

import javax.swing.JButton;

/**
 *
 * @author geoff
 */
public class ModificarAlumnoRellenadoP extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAlumnoRellenadoP
     */
    public ModificarAlumnoRellenadoP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldModificarAlumnoRellenadoPRut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonModificarAlumnoRellenadoPBuscar = new javax.swing.JButton();
        jLabelModificarAlumnoRellenadoPError = new javax.swing.JLabel();

        jLabel1.setText("Ingrese RUT del alumno a modificar:");

        jButtonModificarAlumnoRellenadoPBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonModificarAlumnoRellenadoPBuscar.setText("Buscar");

        jLabelModificarAlumnoRellenadoPError.setText("El RUT ingresado no existe, intente con otro.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jTextFieldModificarAlumnoRellenadoPRut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButtonModificarAlumnoRellenadoPBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabelModificarAlumnoRellenadoPError, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldModificarAlumnoRellenadoPRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabelModificarAlumnoRellenadoPError)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarAlumnoRellenadoPBuscar)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void mostrarjLabelModificarAlumnoRellenadoPError(){
        jLabelModificarAlumnoRellenadoPError.setVisible(true);
    }
    
    public void ocultarjLabelModificarAlumnoRellenadoPError(){
        jLabelModificarAlumnoRellenadoPError.setVisible(false);
    }
    
    public JButton getjButtonModificarAlumnoRellenadoPBuscar(){
        return jButtonModificarAlumnoRellenadoPBuscar;
    }
    
    public String getjTextFieldModificarAlumnoRellenadoPRut(){
        return jTextFieldModificarAlumnoRellenadoPRut.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarAlumnoRellenadoPBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelModificarAlumnoRellenadoPError;
    private javax.swing.JTextField jTextFieldModificarAlumnoRellenadoPRut;
    // End of variables declaration//GEN-END:variables
}
