/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosia.vista.gestionAlumnos;

import javax.swing.JButton;

/**
 *
 * @author geoff
 */
public class ModificarAlumnoEditarP extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAlumnoEditarP
     */
    public ModificarAlumnoEditarP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldModificarAlumnoEditarPNombre = new javax.swing.JTextField();
        jTextFieldModificarAlumnoEditarPCurso = new javax.swing.JTextField();
        jTextFieldModificarAlumnoEditarPRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonModificarAlumnoEditarPActualizar = new javax.swing.JButton();
        jLabelModificarAlumnoEditarPExito = new javax.swing.JLabel();

        jLabel1.setText("Alumno encontrado, a continuación modifique los datos:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Curso:");

        jLabel4.setText("RUT:");

        jButtonModificarAlumnoEditarPActualizar.setText("Actualizar");

        jLabelModificarAlumnoEditarPExito.setText("Alumno modificado con éxito !!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButtonModificarAlumnoEditarPActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldModificarAlumnoEditarPNombre)
                            .addComponent(jTextFieldModificarAlumnoEditarPCurso)
                            .addComponent(jTextFieldModificarAlumnoEditarPRut, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelModificarAlumnoEditarPExito, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelModificarAlumnoEditarPExito)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModificarAlumnoEditarPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModificarAlumnoEditarPCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModificarAlumnoEditarPRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarAlumnoEditarPActualizar)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void ocultarjLabelModificarAlumnoEditarPExito(){
        jLabelModificarAlumnoEditarPExito.setVisible(false);
    }
    
    public void mostrarjLabelModificarAlumnoEditarPExito(){
        jLabelModificarAlumnoEditarPExito.setVisible(true);
    }
    
    public String getjTextFieldModificarAlumnoEditarPNombre(){
        return jTextFieldModificarAlumnoEditarPNombre.getText();
    }
    
    public String getjTextFieldModificarAlumnoEditarPCurso(){
        return jTextFieldModificarAlumnoEditarPCurso.getText();
    }
    
    public String getjTextFieldModificarAlumnoEditarPRut(){
        return jTextFieldModificarAlumnoEditarPRut.getText();
    }
    
    public void setjTextFieldModificarAlumnoEditarPNombre(String nombre){
        jTextFieldModificarAlumnoEditarPNombre.setText(nombre);
    }
    
    public void setjTextFieldModificarAlumnoEditarPCurso(String curso){
        jTextFieldModificarAlumnoEditarPCurso.setText(curso);
    }
    
    public void setjTextFieldModificarAlumnoEditarPRut(String rut){
        jTextFieldModificarAlumnoEditarPRut.setText(rut);
    }
    
    public JButton getjButtonModificarAlumnoEditarPActualizar(){
        return jButtonModificarAlumnoEditarPActualizar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarAlumnoEditarPActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelModificarAlumnoEditarPExito;
    private javax.swing.JTextField jTextFieldModificarAlumnoEditarPCurso;
    private javax.swing.JTextField jTextFieldModificarAlumnoEditarPNombre;
    private javax.swing.JTextField jTextFieldModificarAlumnoEditarPRut;
    // End of variables declaration//GEN-END:variables
}
