/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista.GenerarReportes;

import javax.swing.JButton;

/**
 *
 * @author Bruno Medina
 */
public class GenerarAlumnoV extends javax.swing.JFrame {

    /**
     * Creates new form GenerarAlumnoV
     */
    public GenerarAlumnoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldGenerarAlumnoVRut = new javax.swing.JTextField();
        jButtonGenerarAlumnoVCrear = new javax.swing.JButton();
        jButtonGenerarAlumnoVCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rut del Alumno:");

        jButtonGenerarAlumnoVCrear.setText("Generar Reporte");

        jButtonGenerarAlumnoVCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldGenerarAlumnoVRut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGenerarAlumnoVCancelar)
                    .addComponent(jButtonGenerarAlumnoVCrear))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldGenerarAlumnoVRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jButtonGenerarAlumnoVCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonGenerarAlumnoVCancelar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getjTextFieldGenerarAlumnoVRut(){
        return jTextFieldGenerarAlumnoVRut.getText();
    }
    
    public JButton getjButtonGenerarAlumnoVCrear(){
        return jButtonGenerarAlumnoVCrear;
    }
    
    public JButton getGenerarAlumnoVCancelar(){
        return jButtonGenerarAlumnoVCancelar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarAlumnoVCancelar;
    private javax.swing.JButton jButtonGenerarAlumnoVCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldGenerarAlumnoVRut;
    // End of variables declaration//GEN-END:variables
}
