/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista;

import javax.swing.JButton;

/**
 *
 * @author Bruno Medina
 */
public class AgregarProfesorV extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProfesorV
     */
    public AgregarProfesorV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAgregarProfesorVNombre = new javax.swing.JTextField();
        jTextFieldAgregarProfesorVCurso = new javax.swing.JTextField();
        jTextFieldAgregarProfesorVRut = new javax.swing.JTextField();
        jButtonAgregarProfesorVCrear = new javax.swing.JButton();
        jButtonAgregarProfesorVCancelar = new javax.swing.JButton();
        ocultarjLabelAgregarProfesorVExito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Rut:");

        jLabel3.setText("Curso:");

        jLabel4.setText("Ingrese los datos del Profesor:");

        jTextFieldAgregarProfesorVRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgregarProfesorVRutActionPerformed(evt);
            }
        });

        jButtonAgregarProfesorVCrear.setText("Crear Profesor");

        jButtonAgregarProfesorVCancelar.setText("Cancelar");

        ocultarjLabelAgregarProfesorVExito.setText("Profesor añadido con exito!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAgregarProfesorVCurso)
                                    .addComponent(jTextFieldAgregarProfesorVRut)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAgregarProfesorVNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ocultarjLabelAgregarProfesorVExito))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAgregarProfesorVCrear)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAgregarProfesorVCancelar)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAgregarProfesorVNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(76, 76, 76)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAgregarProfesorVCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldAgregarProfesorVRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarProfesorVCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ocultarjLabelAgregarProfesorVExito)
                .addGap(11, 11, 11)
                .addComponent(jButtonAgregarProfesorVCancelar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAgregarProfesorVRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgregarProfesorVRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgregarProfesorVRutActionPerformed

    // sensibilizacion de botones
    public JButton getjButtonAgregarProfesorVCancelar(){
        return jButtonAgregarProfesorVCancelar;
    }
    
    public JButton getjButtonAgregarProfesorVCrear(){
        return jButtonAgregarProfesorVCrear;
    }
    
    public String getjTextFieldAgregarProfesorVNombre(){
        return jTextFieldAgregarProfesorVNombre.getText();
    }
    
    public String getjTextFieldAgregarProfesorVCurso(){
        return jTextFieldAgregarProfesorVCurso.getText();
    }
        
    public String getjTextFieldAgregarProfesorVRut(){
        return jTextFieldAgregarProfesorVRut.getText();
    }
    
    public void ocultarjLabelAgregarProfesorVExito(){
        ocultarjLabelAgregarProfesorVExito.setVisible(false);
    }
    
    public void mostrarjLabelAgregarProfesorVExito(){
        ocultarjLabelAgregarProfesorVExito.setVisible(true);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProfesorVCancelar;
    private javax.swing.JButton jButtonAgregarProfesorVCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldAgregarProfesorVCurso;
    private javax.swing.JTextField jTextFieldAgregarProfesorVNombre;
    private javax.swing.JTextField jTextFieldAgregarProfesorVRut;
    private javax.swing.JLabel ocultarjLabelAgregarProfesorVExito;
    // End of variables declaration//GEN-END:variables
}
