/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author geoff
 */
public class GestionAlumnosV extends javax.swing.JFrame {

    /**
     * Creates new form GestionAlumnosV
     */
    public GestionAlumnosV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGestionAlumnosVCancelar = new javax.swing.JButton();
        jComboBoxGestionAlumnosVOpciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonGestionAlumnosVIr = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonGestionAlumnosVCancelar.setText("Cancelar");
        jButtonGestionAlumnosVCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAlumnosVCancelarActionPerformed(evt);
            }
        });

        jComboBoxGestionAlumnosVOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar Alumno", "Modificar Alumno", "Eliminar Alumno", "Buscar Alumno" }));
        jComboBoxGestionAlumnosVOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGestionAlumnosVOpcionesActionPerformed(evt);
            }
        });

        jLabel2.setText("Opcion:");

        jButtonGestionAlumnosVIr.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGestionAlumnosVIr.setText("ir");
        jButtonGestionAlumnosVIr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Este es el menu de gestion de alumnos");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGestionAlumnosVCancelar)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxGestionAlumnosVOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGestionAlumnosVIr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGestionAlumnosVOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGestionAlumnosVIr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButtonGestionAlumnosVCancelar)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionAlumnosVCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAlumnosVCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionAlumnosVCancelarActionPerformed

    private void jComboBoxGestionAlumnosVOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGestionAlumnosVOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGestionAlumnosVOpcionesActionPerformed
    
    
    // sensibilizacion de botones
    public JButton getjButtonGestionAlumnosVCancelar(){
        return jButtonGestionAlumnosVCancelar;
    }
    
    public JComboBox getjComboBoxGestionAlumnosVOpciones(){
        return jComboBoxGestionAlumnosVOpciones;
    }
    
    public JButton getjButtonGestionAlumnosVIr(){
        return jButtonGestionAlumnosVIr;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionAlumnosVCancelar;
    private javax.swing.JButton jButtonGestionAlumnosVIr;
    private javax.swing.JComboBox<String> jComboBoxGestionAlumnosVOpciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
