/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista;

import javax.swing.JButton;

/**
 *
 * @author anton
 */
public class GestionAsistenciaV extends javax.swing.JFrame {

    /**
     * Creates new form GestionAsistenciaV1
     */
    public GestionAsistenciaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonGestionAsistenciaVGestionPorCurso = new javax.swing.JButton();
        jButtonGestionAsistenciaVCancelar = new javax.swing.JButton();
        jButtonGestionAsistenciaVModificarFechaAsistencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Menú de gestion de asistencia");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonGestionAsistenciaVGestionPorCurso.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGestionAsistenciaVGestionPorCurso.setText("Gestion por curso");
        jButtonGestionAsistenciaVGestionPorCurso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGestionAsistenciaVGestionPorCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAsistenciaVGestionPorCursoActionPerformed(evt);
            }
        });

        jButtonGestionAsistenciaVCancelar.setText("Cancelar");
        jButtonGestionAsistenciaVCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAsistenciaVCancelarActionPerformed(evt);
            }
        });

        jButtonGestionAsistenciaVModificarFechaAsistencia.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGestionAsistenciaVModificarFechaAsistencia.setText("Modificar fecha asistencia");
        jButtonGestionAsistenciaVModificarFechaAsistencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGestionAsistenciaVModificarFechaAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAsistenciaVModificarFechaAsistenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGestionAsistenciaVCancelar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonGestionAsistenciaVModificarFechaAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jButtonGestionAsistenciaVGestionPorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonGestionAsistenciaVModificarFechaAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonGestionAsistenciaVGestionPorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonGestionAsistenciaVCancelar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionAsistenciaVCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAsistenciaVCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionAsistenciaVCancelarActionPerformed

    private void jButtonGestionAsistenciaVGestionPorCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAsistenciaVGestionPorCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionAsistenciaVGestionPorCursoActionPerformed

    private void jButtonGestionAsistenciaVModificarFechaAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAsistenciaVModificarFechaAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionAsistenciaVModificarFechaAsistenciaActionPerformed

    public JButton getjButtonGestionAsistenciaVCancelar(){
        return jButtonGestionAsistenciaVCancelar;
    }
    
    public JButton getjButtonGestionAsistenciaVGestionPorCurso(){
        return jButtonGestionAsistenciaVGestionPorCurso;
    }
    
    public JButton getjButtonGestionAsistenciaVModificarFechaAsistencia(){
        return jButtonGestionAsistenciaVModificarFechaAsistencia;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionAsistenciaVCancelar;
    private javax.swing.JButton jButtonGestionAsistenciaVGestionPorCurso;
    private javax.swing.JButton jButtonGestionAsistenciaVModificarFechaAsistencia;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
