/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author anton
 */
public class GestionAsistenciaV1 extends javax.swing.JFrame {

    /**
     * Creates new form GestionAsistenciaV1
     */
    public GestionAsistenciaV1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGestionAsistenciaVCancelar = new javax.swing.JButton();
        jEliminarAsistenciaP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonGestionAsistenciaVCancelar.setText("Cancelar");
        jButtonGestionAsistenciaVCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAsistenciaVCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jEliminarAsistenciaPLayout = new javax.swing.GroupLayout(jEliminarAsistenciaP);
        jEliminarAsistenciaP.setLayout(jEliminarAsistenciaPLayout);
        jEliminarAsistenciaPLayout.setHorizontalGroup(
            jEliminarAsistenciaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jEliminarAsistenciaPLayout.setVerticalGroup(
            jEliminarAsistenciaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jButtonGestionAsistenciaVCancelar)
                .addGap(22, 22, 22))
            .addComponent(jEliminarAsistenciaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jEliminarAsistenciaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGestionAsistenciaVCancelar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionAsistenciaVCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAsistenciaVCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGestionAsistenciaVCancelarActionPerformed

    public JButton getjButtonGestionAsistenciaVCancelar(){
        return jButtonGestionAsistenciaVCancelar;
    }
    
    public JButton getjButtonGestionAsistenciaVIr(){
        return jButtonGestionAsistenciaVIr;
    }
    
    public JComboBox getjComboBoxGestionAsistenciaVSeleccion(){
        return jComboBoxGestionAsistenciaVSeleccion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionAsistenciaVCancelar;
    private javax.swing.JPanel jEliminarAsistenciaP;
    // End of variables declaration//GEN-END:variables
}
