/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista;

import javax.swing.JButton;

/**
 *
 * @author anton
 */
public class MenuProfesorV extends javax.swing.JFrame {

    /**
     * Creates new form MenuProfesorV
     */
    public MenuProfesorV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonMenuProfesorVEliminar = new javax.swing.JButton();
        jButtonMenuProfesorVAgregar = new javax.swing.JButton();
        jButtonMenuProfesorVModificar = new javax.swing.JButton();
        jButtonMenuProfesorVCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(671, 440));

        jLabel1.setFont(new java.awt.Font("Quicksand", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modulo Profesores");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDoubleBuffered(true);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Quicksand", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Opciones");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonMenuProfesorVEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMenuProfesorVEliminar.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jButtonMenuProfesorVEliminar.setText("Eliminar Profesor");
        jButtonMenuProfesorVEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMenuProfesorVEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProfesorVEliminarActionPerformed(evt);
            }
        });

        jButtonMenuProfesorVAgregar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMenuProfesorVAgregar.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jButtonMenuProfesorVAgregar.setText("Agregar Profesor");
        jButtonMenuProfesorVAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMenuProfesorVAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProfesorVAgregarActionPerformed(evt);
            }
        });

        jButtonMenuProfesorVModificar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMenuProfesorVModificar.setFont(new java.awt.Font("Quicksand", 0, 12)); // NOI18N
        jButtonMenuProfesorVModificar.setText("Modificar Profesor");
        jButtonMenuProfesorVModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonMenuProfesorVModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuProfesorVModificarActionPerformed(evt);
            }
        });

        jButtonMenuProfesorVCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMenuProfesorVEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMenuProfesorVAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonMenuProfesorVModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonMenuProfesorVCancelar)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMenuProfesorVAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMenuProfesorVEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonMenuProfesorVModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButtonMenuProfesorVCancelar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuProfesorVEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProfesorVEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuProfesorVEliminarActionPerformed

    private void jButtonMenuProfesorVAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProfesorVAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuProfesorVAgregarActionPerformed

    private void jButtonMenuProfesorVModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuProfesorVModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuProfesorVModificarActionPerformed

    public JButton getjButtonMenuProfesorVCancelar(){
        return jButtonMenuProfesorVCancelar;
    }
    
    public JButton getjButtonMenuProfesorVAgregar(){
        return jButtonMenuProfesorVAgregar;
    }
    
    public JButton getjButtonMenuProfesorVEliminar(){
        return jButtonMenuProfesorVEliminar;
    }
    
    public JButton getjButtonMenuProfesorVModificar(){
        return jButtonMenuProfesorVModificar;
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMenuProfesorVAgregar;
    private javax.swing.JButton jButtonMenuProfesorVCancelar;
    private javax.swing.JButton jButtonMenuProfesorVEliminar;
    private javax.swing.JButton jButtonMenuProfesorVModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
