/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista.GestionAsistencia;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author geoff
 */
public class GestionTotalAsistenciaV extends javax.swing.JFrame {

    /**
     * Creates new form GestionTotalAsistencia
     */
    public GestionTotalAsistenciaV() {
        initComponents();
        
        jTableGestionTotalAsistenciaVTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] { "Nombre", "RUT", "Estado asistencia" }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldGestionTotalAsistenciaVFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGestionTotalAsistenciaVTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonGestionTotalAsistenciaVBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonGestionTotalAsistenciaVSalir = new javax.swing.JButton();
        jButtonGestionTotalAsistenciaVBorrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxGestionTotalAsistenciaVCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldGestionTotalAsistenciaVFecha.setText("dd-mm-yyyy");
        jTextFieldGestionTotalAsistenciaVFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGestionTotalAsistenciaVFechaActionPerformed(evt);
            }
        });

        jTableGestionTotalAsistenciaVTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Rut", "Estado asistencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableGestionTotalAsistenciaVTabla);
        if (jTableGestionTotalAsistenciaVTabla.getColumnModel().getColumnCount() > 0) {
            jTableGestionTotalAsistenciaVTabla.getColumnModel().getColumn(0).setPreferredWidth(260);
        }

        jLabel1.setText("Fecha:");

        jButtonGestionTotalAsistenciaVBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGestionTotalAsistenciaVBuscar.setText("Buscar");

        jLabel2.setText("Curso:");

        jButtonGestionTotalAsistenciaVSalir.setBackground(new java.awt.Color(231, 231, 231));
        jButtonGestionTotalAsistenciaVSalir.setText("Guardar y salir");

        jButtonGestionTotalAsistenciaVBorrar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonGestionTotalAsistenciaVBorrar.setText("Borrar");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jLabel3.setText("* rellene los campos de Fecha y Curso, luego presione \"Buscar\"");

        jComboBoxGestionTotalAsistenciaVCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuarto medio", "Tercero medio", "Segundo medio", "Primero medio", "Octavo basico", "Septimo basico", "Sexto basico", "Quinto basico", "Cuarto basico", "Tercero basico", "Segundo basico", "Primero basico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldGestionTotalAsistenciaVFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGestionTotalAsistenciaVBuscar)
                .addGap(173, 173, 173)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxGestionTotalAsistenciaVCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButtonGestionTotalAsistenciaVBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButtonGestionTotalAsistenciaVSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGestionTotalAsistenciaVFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonGestionTotalAsistenciaVBuscar)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxGestionTotalAsistenciaVCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGestionTotalAsistenciaVSalir)
                    .addComponent(jButtonGestionTotalAsistenciaVBorrar)
                    .addComponent(jLabel3))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGestionTotalAsistenciaVFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGestionTotalAsistenciaVFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGestionTotalAsistenciaVFechaActionPerformed
    
    public JButton getjButtonGestionTotalAsistenciaVBorrar(){
        return jButtonGestionTotalAsistenciaVBorrar;
    }
    
    public JButton getjButtonGestionTotalAsistenciaVBuscar(){
        return jButtonGestionTotalAsistenciaVBuscar;
    }
    
    public JButton getjButtonGestionTotalAsistenciaVSalir(){
        return jButtonGestionTotalAsistenciaVSalir;
    }
    
    public JTable getjTableGestionTotalAsistenciaVTabla(){
        return jTableGestionTotalAsistenciaVTabla;
    }

    // Getter para el campo de texto de la fecha
    public JTextField getjTextFieldGestionTotalAsistenciaVFecha() {
        return jTextFieldGestionTotalAsistenciaVFecha;
    }

    // Getter para el campo de texto del curso
    public JComboBox<String> getjComboBoxGestionTotalAsistenciaVCurso() {
        return jComboBoxGestionTotalAsistenciaVCurso;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionTotalAsistenciaVBorrar;
    private javax.swing.JButton jButtonGestionTotalAsistenciaVBuscar;
    private javax.swing.JButton jButtonGestionTotalAsistenciaVSalir;
    private javax.swing.JComboBox<String> jComboBoxGestionTotalAsistenciaVCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGestionTotalAsistenciaVTabla;
    private javax.swing.JTextField jTextFieldGestionTotalAsistenciaVFecha;
    // End of variables declaration//GEN-END:variables
}
