/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosia.vista.GestionAsistencia;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author geoff
 */
public class ModificarFechaAsistenciaEditarP extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAlumnoEditarP
     */
    public ModificarFechaAsistenciaEditarP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonModificarFechaAsistenciaEditarPActualizar = new javax.swing.JButton();
        jLabelModificarFechaAsistenciaEditarPExito = new javax.swing.JLabel();
        jComboBoxModificarFechaAs = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldModificarFechaAsistenciaEditarPFecha = new javax.swing.JTextField();

        jLabel1.setText("Fecha de asistencia encontrada, a continuación modifique los datos:");

        jLabel2.setText("Estado asistencia:");

        jButtonModificarFechaAsistenciaEditarPActualizar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonModificarFechaAsistenciaEditarPActualizar.setText("Actualizar");

        jLabelModificarFechaAsistenciaEditarPExito.setText("Fecha modificada con éxito !!");

        jComboBoxModificarFechaAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRESENTE", "AUSENTE", "JUSTIFICADO" }));

        jLabel3.setText("Ingrese nueva fecha de la asistencia:");

        jTextFieldModificarFechaAsistenciaEditarPFecha.setText("dd-mm-yyyy");
        jTextFieldModificarFechaAsistenciaEditarPFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModificarFechaAsistenciaEditarPFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelModificarFechaAsistenciaEditarPExito, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButtonModificarFechaAsistenciaEditarPActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldModificarFechaAsistenciaEditarPFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxModificarFechaAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabelModificarFechaAsistenciaEditarPExito)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxModificarFechaAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldModificarFechaAsistenciaEditarPFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButtonModificarFechaAsistenciaEditarPActualizar)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldModificarFechaAsistenciaEditarPFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModificarFechaAsistenciaEditarPFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModificarFechaAsistenciaEditarPFechaActionPerformed
    public void ocultarjLabelModificarFechaAsistenciaEditarPExito(){
        jLabelModificarFechaAsistenciaEditarPExito.setVisible(false);
    }
    
    public void mostrarjLabelModificarFechaAsistenciaEditarPExito(){
        jLabelModificarFechaAsistenciaEditarPExito.setVisible(true);
    }
    
    
    public JButton getjButtonModificarFechaAsistenciaEditarPActualizar(){
        return jButtonModificarFechaAsistenciaEditarPActualizar;
    }
    
    public JTextField getjTextFieldModificarFechaAsistenciaEditarPFecha(){
        return jTextFieldModificarFechaAsistenciaEditarPFecha;
    }
    
    public JComboBox<String> getjComboBoxModificarFechaAs(){
        return jComboBoxModificarFechaAs;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarFechaAsistenciaEditarPActualizar;
    private javax.swing.JComboBox<String> jComboBoxModificarFechaAs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelModificarFechaAsistenciaEditarPExito;
    private javax.swing.JTextField jTextFieldModificarFechaAsistenciaEditarPFecha;
    // End of variables declaration//GEN-END:variables
}
