/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectosia.vista.GestionAsistencia;

import com.mycompany.proyectosia.vista.gestionAlumnos.*;
import javax.swing.JButton;

/**
 *
 * @author geoff
 */
public class ModificarFechaAsistenciaRellenadoP extends javax.swing.JPanel {

    /**
     * Creates new form ModificarAlumnoRellenadoP
     */
    public ModificarFechaAsistenciaRellenadoP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldModificarFechaAsistenciaPFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonModificarFechaAsistenciaPBuscar = new javax.swing.JButton();
        jLabelModificarFechaAsistenciaRellenadoPError = new javax.swing.JLabel();
        jTextFieldModificarFechaAsistenciaPRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Ingrese fecha de la asistencia a modificar:");

        jButtonModificarFechaAsistenciaPBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jButtonModificarFechaAsistenciaPBuscar.setText("Buscar");

        jLabelModificarFechaAsistenciaRellenadoPError.setText("Los datos ingresados no existen, intente con otros.");

        jLabel2.setText("Ingrese rut del alumno a mover la asistencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 80, Short.MAX_VALUE)
                        .addComponent(jLabelModificarFechaAsistenciaRellenadoPError, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jButtonModificarFechaAsistenciaPBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jTextFieldModificarFechaAsistenciaPRut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jTextFieldModificarFechaAsistenciaPFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldModificarFechaAsistenciaPRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldModificarFechaAsistenciaPFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelModificarFechaAsistenciaRellenadoPError)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarFechaAsistenciaPBuscar)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void mostrarjLabelModificarFechaAsistenciaRellenadoPError(){
        jLabelModificarFechaAsistenciaRellenadoPError.setVisible(true);
    }
    
    public void ocultarjLabelModificarFechaAsistenciaRellenadoPError(){
        jLabelModificarFechaAsistenciaRellenadoPError.setVisible(false);
    }
    
    public JButton getjButtonModificarFechaAsistenciaPBuscar(){
        return jButtonModificarFechaAsistenciaPBuscar;
    }
    
    public String getjTextFieldModificarFechaAsistenciaPFecha(){
        return jTextFieldModificarFechaAsistenciaPFecha.getText();
    }
    
    public String getjTextFieldModificarFechaAsistenciaPRut(){
        return jTextFieldModificarFechaAsistenciaPRut.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarFechaAsistenciaPBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelModificarFechaAsistenciaRellenadoPError;
    private javax.swing.JTextField jTextFieldModificarFechaAsistenciaPFecha;
    private javax.swing.JTextField jTextFieldModificarFechaAsistenciaPRut;
    // End of variables declaration//GEN-END:variables
}
