/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectosia.vista.GestionAsistencia;

import com.mycompany.proyectosia.vista.gestionAlumnos.*;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author geoff
 */
public class ModificarFechaAsistenciaV extends javax.swing.JFrame {

    /**
     * Creates new form ModificarAlumnoV
     */
    public ModificarFechaAsistenciaV() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButtonModificarFechaAsistenciaVCancelar = new javax.swing.JButton();
        jPanelModificarFechaAsistenciaVPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Quicksand", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Modificar fecha asistencia");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonModificarFechaAsistenciaVCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanelModificarFechaAsistenciaVPrincipalLayout = new javax.swing.GroupLayout(jPanelModificarFechaAsistenciaVPrincipal);
        jPanelModificarFechaAsistenciaVPrincipal.setLayout(jPanelModificarFechaAsistenciaVPrincipalLayout);
        jPanelModificarFechaAsistenciaVPrincipalLayout.setHorizontalGroup(
            jPanelModificarFechaAsistenciaVPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanelModificarFechaAsistenciaVPrincipalLayout.setVerticalGroup(
            jPanelModificarFechaAsistenciaVPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModificarFechaAsistenciaVCancelar)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanelModificarFechaAsistenciaVPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 91, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelModificarFechaAsistenciaVPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonModificarFechaAsistenciaVCancelar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    public void mostrarjPanelModificarAlumnoVPrincipal(){
    jPanelModificarAlumnoVInformacionRellenar.setVisible(true);
}

public void ocultarjPanelModificarAlumnoVPrincipal(){
    jPanelModificarAlumnoVInformacionRellenar.setVisible(false);
}

public String getjTextFieldModificarAlumnoVRutBuscar(){
    return jTextFieldModificarAlumnoVRutBuscar.getText();
}

public JButton getjButtonModificarAlumnoVBuscar(){
    return jButtonModificarAlumnoVBuscar;
}
*/
public JButton getjButtonModificarFechaAsistenciaVCancelar(){
    return jButtonModificarFechaAsistenciaVCancelar;
}

public JPanel getjPanelModificarFechaAsistenciaVPrincipal(){
    return jPanelModificarFechaAsistenciaVPrincipal;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarFechaAsistenciaVCancelar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelModificarFechaAsistenciaVPrincipal;
    // End of variables declaration//GEN-END:variables
}
